tezos:
  host: 127.0.0.1
  port: 8765

server:
  port: 8899

proxy:
  readTimeout: 1
  writeTimeout: 5
  idleTimeout: 120
  whitelistedMethods:
    - /chains/main/blocks(.*?)
  blockedMethods:
    - (.*?)context/contracts$
    - /monitor(.*?)
    - /netowork(.*?)
  dontCache:
    - (.*?)/head/(.*?)
  rateLimitPeriod: 100
  rateLimitCount: 100
  cacheMaxItems: 2000